%Question 2a
Coeff = g_smooth2(5);
figure(1)
subplot(1,2,1);
imagesc(Coeff);
title('Coefficients Generated By Gsmooth2(5)');
subplot(1,2,2);
surf(Coeff);
title('Surface Plot of Coefficients');

%question 2b
peppers = imread('peppers.tif');
peppers_noises1 = imread('peppers_noise1.tif');
[w,h] = size(peppers);
figure(2);
subplot(1,2,1);
imagesc(peppers);
colorbar;
subplot(1,2,2);
imagesc(peppers_noises1);
colorbar;

SM_err = sum(sum((peppers - peppers_noises1).^2))/(w*h);
display(SM_err);

%SM_err =
%78.5430
